在MATLAB里，`*` 代表矩阵乘法。但是在numpy里，`*`表示element-wise prodct。要想做到矩阵乘法，要用多函数dot:

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

`x.dot(y)`等同于`np.dot(x, y)`:

In [6]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

一个二维数组和一个一维数组的矩阵乘法，得到一个一维数组：

In [7]:
np.dot(x, np.ones(3))  
# 这里应该是用了boradcasting，x中的每一行与[1, 1, 1]点对点乘积后求和

array([ 6., 15.])

`@`作为一个中缀计算符（鬼知道这是什么东西），也能实现矩阵乘法：

In [8]:
x @ np.ones(3)

array([ 6., 15.])

`np.linalg`能用来做矩阵分解，以及比如转置和求秩之类的事情：

In [9]:
from numpy.linalg import inv, qr

In [10]:
# X = np.round(np.random.randn(5, 5), 3) # 这里我们用np.round控制小数点后的位数，看起来更舒服一些
X = np.random.randn(5, 5)
X

array([[-0.15714295, -0.60839105,  0.7120679 ,  0.49319778, -0.10481843],
       [ 1.45185496, -0.26646153, -0.26413488,  0.83369993,  0.20396625],
       [-1.49369709,  0.5396138 , -1.38008963, -0.38767062,  1.49311315],
       [-1.39410701, -0.60898056,  1.18870289,  0.12952705, -1.00207238],
       [ 0.9781983 , -0.67306743, -2.13371184, -0.7313506 ,  0.99995004]])

In [11]:
mat = X.T.dot(X)
np.round(mat, 2)

array([[ 7.26, -0.91, -2.18,  0.82,  0.46],
       [-0.91,  1.56, -0.4 , -0.32,  0.75],
       [-2.18, -0.4 ,  8.45,  2.38, -5.51],
       [ 0.82, -0.32,  2.38,  1.64, -1.32],
       [ 0.46,  0.75, -5.51, -1.32,  4.29]])

In [12]:
np.round(inv(mat), 2)

array([[ 0.58, -0.24,  1.42, -1.25,  1.42],
       [-0.24,  1.07, -1.2 ,  0.92, -1.42],
       [ 1.42, -1.2 ,  4.85, -3.86,  5.11],
       [-1.25,  0.92, -3.86,  3.98, -3.77],
       [ 1.42, -1.42,  5.11, -3.77,  5.74]])

In [13]:
np.round(mat.dot(inv(mat)), 2)

array([[ 1., -0., -0.,  0., -0.],
       [-0.,  1., -0.,  0., -0.],
       [-0., -0.,  1.,  0., -0.],
       [-0., -0.,  0.,  1.,  0.],
       [-0.,  0., -0.,  0.,  1.]])

In [14]:
q, r = qr(mat)

In [15]:
np.round(r, 2)

array([[-7.69,  0.92,  4.48, -0.23, -2.02],
       [ 0.  , -1.8 ,  6.12,  1.94, -4.69],
       [ 0.  ,  0.  , -7.41, -2.54,  4.98],
       [ 0.  ,  0.  ,  0.  , -0.78, -0.6 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.11]])

`X.T.dot(X)`计算的是X和X的转置的矩阵乘法。

一些常用的numpy.linalg函数：

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/3jol9.png)

![](http://oydgk2hgw.bkt.clouddn.com/pydata-book/5nfep.png)